baseURL = "https://boilerplate"
languageCode = "en-us"
title = "Project Title"
theme = "docsy"
contentDir = "content"

[params]
time_format_blog = "Monday, January 02, 2006"
time_format_default = "January 2, 2006"
# Sections to publish in the main RSS feed.
rss_sections = ["blog"]
offlineSearch = true

[params.print]
disable_toc = false

[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = false
sidebar_menu_foldable = true
sidebar_cache_limit = 10
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = false
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = false

[params.plantuml]
enable = true
theme = "default"

#Set url to plantuml server 
#default is http://www.plantuml.com/plantuml/svg/
svg_image_url = "https://www.plantuml.com/plantuml/svg/"


# For a full list of parameters used in Docsy sites, see:
# https://github.com/google/docsy-example/blob/master/config.toml


[outputFormats]
[outputFormats.PRINT]
baseName = "index"
isHTML = true
mediaType = "text/html"
path = "_print"
permalinkable = false

[outputs]
   home = ["HTML", "RSS", "print"]
   section = ["HTML", "RSS", "print"]


[menu]
    [[menu.main]]
        name = "Changelog"
        url = "/CHANGELOG"
        weight = 2

    [[menu.main]]
        name = "Back"
        url = "https://ringsq.dev/docs/services"
        weight = 1



# Markup configure section
# See https://gohugo.io/getting-started/configuration-markup/
[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.goldmark.renderer]
        unsafe= true
    [markup.tableOfContents]
        startLevel = 2
        endLevel = 6
        ordered = false

